### ISSUE TITLE
My Puffle / Games Color Issue / Sled Racing

### ISSUE THREAD

**Issue by tootyta** [ShawnTD/Luna#2]
These both were opened on the titshacking/Luna but then closed due to loss of support from that one.

1. So when I play a Game such as Hydro Hopper, it's supposed to match my penguin color. Instead, every time it shows black. Same with the game PBL My Puffle. My puffle is always blue even when I walk a for example... Pink Puffle.

2. Sled Racing doesn't work... I wish at least one mini-game would work to a nice extent.

Edit to 2, the only reason why I'm not asking about other games is because I have to say that Sled Racing is the 2nd best multiplayer game (other than Card-Jitsu). Also, is Card-Jitsu gonna be added? I saw some start handlers for it, like loading the player cards!

**Comment by ShawnTD** [comment]
The sled racing does work but you have to tweek it a bit for it to work and Card Jitsu will be implemented soon. I don't know about the Penguin Colors for the games

**Comment by tootyta** [comment]
Okay, by tweak it you mean??? Like what do I have to do with it, I don't have much knowledge with perl, so do you think you could help me through the process?

**Comment by ShawnTD** [comment]
I could but I have a question. When you exit your game doesn't stay stuck on the loader screen or proceeds to the coin amount display when you end the game.

**Comment by tootyta** [comment]
It proceeds to the coin amount, the reason some people might be getting an infinite loader is because of the interface... Just in case, I would use both handlers for games so that way both users don't get this error. I know some AS (ActionScript) :P

**Comment by ShawnTD** [comment]
Yea I know ActionScript very well but I was just asking in the case of it was only me. I'm sure aware it was the Interface xd.

**Comment by tootyta** [comment]
Alright. I'm excited for the addon of Card-Jitsu... I also hope Find Four Winning will work soon too :P, that's a weird one lol. Anyways, tell me when you can help with getting Sled Racing to work.

**Comment by ShawnTD** [comment]
What is the other handler for games?

**Comment by tootyta** [comment]
Huh? I'm a bit confused on what you're asking for... The handler for the new way of handling the endgame or the old one?

**Comment by ShawnTD** [comment]
The old way

**Comment by tootyta** [comment]
Hmm, I'm not sure... Since Luna didn't work with the old way, I've modified my interface to have the new way. If you're looking for the handler from a source, I'm not sure what to say... You could try looking in other sources or using the interface you have...

**Comment by tootyta** [comment]
Hey, I forgot to ask.. Do you have Skype, it would probably be easier to talk through there.

**Comment by ShawnTD** [comment]
I use Discord https://discord.gg/xFMkg but my skype is bossfromrealcp

**Comment by tootyta** [comment]
I tried Discord but I don't really know how to use it and add people so I sent you a request on Skype.
