### ISSUE TITLE
Weird Message Glitch

### ISSUE THREAD

**Issue by tootyta** [ShawnTD/Luna#4]
So here's a scenario... Player 1 and Player 2 are talking... Player 1 says hi... Player 2 says hi back but Player 1's message gets cut off. This is due to two packets sending to the server and one knocking the other one out on the player's screen. I've tried fixing this myself and looked at the method for sendRoom... But I've only managed to fix it for 2 players in a room. It sends a packet for every player in the room. So if there are 6 people in the room, it sends six packets for one person's message.  I thought it was the foreach but idk... Please get this fixed soon. Even Nova has this working lol.

**Comment by ShawnTD** [comment]
It doesn't seem to happen to me so
